[package]
name = "pxlsspace_native"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
path = "addons/index.rs"

[profile.release]
lto = true

[dependencies]
napi = "1"
napi-derive = "1"
rayon = "1.5.1"
num_cpus = "1.13.0"
num-traits = "0.2.8"

[build-dependencies]
napi-build = "1"